language: csharp
mono: none
dotnet: 2.1.2
solution: Sanatana.Timers.sln
script:
  - dotnet pack Sanatana.Timers/Sanatana.Timers.csproj -o ../nuget -c Release -v n
  - dotnet nuget push nuget/Sanatana.Timers.*.nupkg --force-english-output -k $NUGET_API_KEY --source https://api.nuget.org/v3/index.json